// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase is auxiliary (auth/history/replay), not the gameplay authority. When
// its env is absent (e.g. CI preview builds), fall back to harmless placeholders
// so createClient() doesn't throw "supabaseUrl is required" at import and crash
// the whole app. Supabase-backed calls then fail gracefully instead of blanking
// the page. Real values are injected from .env at build time.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key';
if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[supabase] VITE_SUPABASE_URL/KEY missing — auth/history/replay disabled.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});